### PR TITLE
adds week-002 issue

### PR DESCRIPTION
**Pull request by sendilkumarn**
r? @fitzgen

### CODE REVIEW

**Comment by sendilkumarn** [comment]
I totally forgot about `template.md` 😞

**Comment by fitzgen** [comment]
Would you like to send out the tweets and post to users.rust-lang.org and r/rust, or should I?

**Comment by sendilkumarn** [comment]
I am on it ❤️ 

Taking over 😜

**Comment by sendilkumarn** [comment]
just to add it in here https://users.rust-lang.org/t/webassembly-rust-and-now/17238/13

**Comment by mgattozzi** [comment]
Thanks for doing this @sendilkumarn :)

**Pull request merged**
